version: '3'
services:
  backend:
    build: ./media-app-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build: ./media-app-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
